version: "3.1"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.1
    ports:
      - "8083:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

  app:
    build: .
    ports:
        - "9095:9090" #<local-port>:<container-port>
